/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import model.Project;
import model.Task;
import util.ButtonColumnCellRederer;
import util.DeadlineColumnCellRenderer;
import util.TaskTableModel;

/**
 *
 * @author vinicius.santos
 */
public class MainScreen extends javax.swing.JFrame {

    ProjectController projectController;
    TaskController taskController;
    
    DefaultListModel projecstModel;
    TaskTableModel taskModel;
    
    public MainScreen() {
        initComponents();
        
        initDataController();
        initComponentsModel();
        
        decotareTableTasks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1Tasks = new javax.swing.JScrollPane();
        jTable1TableTasks = new javax.swing.JTable();
        jPanel1ToolBar = new javax.swing.JPanel();
        jLabel1TooBarTitle = new javax.swing.JLabel();
        jLabel2ToolBarSubtitle = new javax.swing.JLabel();
        jPanel2Projects = new javax.swing.JPanel();
        jLabel3ProjectsTitle = new javax.swing.JLabel();
        jLabel5ProjectsAdd = new javax.swing.JLabel();
        jPanel3Tasks = new javax.swing.JPanel();
        jLabel4TasksTitle = new javax.swing.JLabel();
        jLabel6TasksAdd = new javax.swing.JLabel();
        jPanel4ProjectList = new javax.swing.JPanel();
        jScrollPane1Projects = new javax.swing.JScrollPane();
        jList1Projects = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6EmptyList = new javax.swing.JPanel();
        jLabel7EmptyListaIcon = new javax.swing.JLabel();
        jLabel8EmptyListTitle = new javax.swing.JLabel();
        jLabel9EmptyListSubTitle = new javax.swing.JLabel();

        jTable1TableTasks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1TableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1TableTasks.setGridColor(java.awt.Color.white);
        jTable1TableTasks.setRowHeight(50);
        jTable1TableTasks.setSelectionBackground(new java.awt.Color(153, 255, 255));
        jTable1TableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1TableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1TableTasksMouseClicked(evt);
            }
        });
        jScrollPane1Tasks.setViewportView(jTable1TableTasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 1024));
        setPreferredSize(new java.awt.Dimension(1024, 800));

        jPanel1ToolBar.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1ToolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1TooBarTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1TooBarTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1TooBarTitle.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinicius.santos\\Documents\\NetBeansProjects\\projectManagerApp\\app\\src\\main\\icons\\innovation.png")); // NOI18N
        jLabel1TooBarTitle.setText(" Project Manager App");

        jLabel2ToolBarSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2ToolBarSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2ToolBarSubtitle.setText("Anote tudo, não esqueça nada...");

        javax.swing.GroupLayout jPanel1ToolBarLayout = new javax.swing.GroupLayout(jPanel1ToolBar);
        jPanel1ToolBar.setLayout(jPanel1ToolBarLayout);
        jPanel1ToolBarLayout.setHorizontalGroup(
            jPanel1ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ToolBarLayout.createSequentialGroup()
                .addGroup(jPanel1ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1ToolBarLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2ToolBarSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1ToolBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1TooBarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1ToolBarLayout.setVerticalGroup(
            jPanel1ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ToolBarLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel1TooBarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2ToolBarSubtitle)
                .addGap(28, 28, 28))
        );

        jPanel2Projects.setBackground(java.awt.Color.white);
        jPanel2Projects.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3ProjectsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3ProjectsTitle.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3ProjectsTitle.setText("Projetos");

        jLabel5ProjectsAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinicius.santos\\Documents\\NetBeansProjects\\projectManagerApp\\app\\src\\main\\icons\\add2.png")); // NOI18N
        jLabel5ProjectsAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5ProjectsAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2ProjectsLayout = new javax.swing.GroupLayout(jPanel2Projects);
        jPanel2Projects.setLayout(jPanel2ProjectsLayout);
        jPanel2ProjectsLayout.setHorizontalGroup(
            jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3ProjectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5ProjectsAdd)
                .addContainerGap())
        );
        jPanel2ProjectsLayout.setVerticalGroup(
            jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3ProjectsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2ProjectsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5ProjectsAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3Tasks.setBackground(java.awt.Color.white);
        jPanel3Tasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4TasksTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4TasksTitle.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4TasksTitle.setText("Tarefas");

        jLabel6TasksAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinicius.santos\\Documents\\NetBeansProjects\\projectManagerApp\\app\\src\\main\\icons\\add2.png")); // NOI18N
        jLabel6TasksAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6TasksAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3TasksLayout = new javax.swing.GroupLayout(jPanel3Tasks);
        jPanel3Tasks.setLayout(jPanel3TasksLayout);
        jPanel3TasksLayout.setHorizontalGroup(
            jPanel3TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3TasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4TasksTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6TasksAdd)
                .addContainerGap())
        );
        jPanel3TasksLayout.setVerticalGroup(
            jPanel3TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3TasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4TasksTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6TasksAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4ProjectList.setBackground(java.awt.Color.white);
        jPanel4ProjectList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList1Projects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jList1Projects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1Projects.setFixedCellHeight(50);
        jList1Projects.setSelectionBackground(new java.awt.Color(153, 255, 255));
        jList1Projects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1ProjectsMouseClicked(evt);
            }
        });
        jScrollPane1Projects.setViewportView(jList1Projects);

        javax.swing.GroupLayout jPanel4ProjectListLayout = new javax.swing.GroupLayout(jPanel4ProjectList);
        jPanel4ProjectList.setLayout(jPanel4ProjectListLayout);
        jPanel4ProjectListLayout.setHorizontalGroup(
            jPanel4ProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4ProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1Projects)
                .addContainerGap())
        );
        jPanel4ProjectListLayout.setVerticalGroup(
            jPanel4ProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4ProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1Projects)
                .addContainerGap())
        );

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6EmptyList.setBackground(java.awt.Color.white);
        jPanel6EmptyList.setPreferredSize(new java.awt.Dimension(430, 265));

        jLabel7EmptyListaIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7EmptyListaIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\vinicius.santos\\Documents\\NetBeansProjects\\projectManagerApp\\app\\src\\main\\icons\\task.png")); // NOI18N
        jLabel7EmptyListaIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7EmptyListaIcon.setPreferredSize(new java.awt.Dimension(430, 128));

        jLabel8EmptyListTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8EmptyListTitle.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8EmptyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8EmptyListTitle.setText("Nenhuma tarefa por aqui :D");
        jLabel8EmptyListTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel9EmptyListSubTitle.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9EmptyListSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9EmptyListSubTitle.setText("Clique no botão \"+\" para adicionar uma nova tarefa");
        jLabel9EmptyListSubTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6EmptyListLayout = new javax.swing.GroupLayout(jPanel6EmptyList);
        jPanel6EmptyList.setLayout(jPanel6EmptyListLayout);
        jPanel6EmptyListLayout.setHorizontalGroup(
            jPanel6EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7EmptyListaIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8EmptyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6EmptyListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9EmptyListSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6EmptyListLayout.setVerticalGroup(
            jPanel6EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6EmptyListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7EmptyListaIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8EmptyListTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9EmptyListSubTitle)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6EmptyList, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2Projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4ProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3Tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2Projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3Tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4ProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5ProjectsAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5ProjectsAddMouseClicked
    
        // TODO add your handling code here:
        ProjectDialogScreen  projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);
        
        projectDialogScreen.addWindowListener(new WindowAdapter() {
            
            public void windowClosed(WindowEvent e) { 
                loadProjects();
            }
        });
    }//GEN-LAST:event_jLabel5ProjectsAddMouseClicked

    private void jLabel6TasksAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6TasksAddMouseClicked
        // TODO add your handling code here:
        
        TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
       
        int projectIndex = jList1Projects.getSelectedIndex();
        Project project = (Project) projecstModel.get(projectIndex);
        taskDialogScreen.setProject(project);
        
        taskDialogScreen.setVisible(true);
        
        taskDialogScreen.addWindowListener(new WindowAdapter() {
            
            public void windowClosed(WindowEvent e) { 
                
                int projectIndex = jList1Projects.getSelectedIndex();
                Project project = (Project) projecstModel.get(projectIndex);
                loadTasks(project.getId());
            }
        });
    }//GEN-LAST:event_jLabel6TasksAddMouseClicked

    private void jTable1TableTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1TableTasksMouseClicked
        // TODO add your handling code here:
        
        int rowIndex = jTable1TableTasks.rowAtPoint(evt.getPoint());
        int columnIndex = jTable1TableTasks.columnAtPoint(evt.getPoint());
        Task task = taskModel.getTasks().get(rowIndex);
        
        switch (columnIndex) {
            case 3:
                taskController.update(task);
                break;
            case 4:
                break;
            case 5:
                taskController.removeById(task.getId());
                taskModel.getTasks().remove(task);
                
                int projectIndex = jList1Projects.getSelectedIndex();
                Project project = (Project) projecstModel.get(projectIndex);
                loadTasks(project.getId());
                
                break;
        }
    }//GEN-LAST:event_jTable1TableTasksMouseClicked

    private void jList1ProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1ProjectsMouseClicked
        // TODO add your handling code here:
        
        int projectIndex = jList1Projects.getSelectedIndex();
        Project project = (Project)projecstModel.get(projectIndex);
        loadTasks(project.getId());
    }//GEN-LAST:event_jList1ProjectsMouseClicked
     
    /**
     * @param args the command line arguments
     */
    
    private void showJTableTasks (boolean hasTasks) {
        if(hasTasks) {
            if(jPanel6EmptyList.isVisible()) {
                jPanel6EmptyList.setVisible(false);
                jPanel5.remove(jPanel6EmptyList);
            }
            
            jPanel5.add(jScrollPane1Tasks);
            jScrollPane1Tasks.setVisible(true);
            jScrollPane1Tasks.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        } else {
            if(jScrollPane1Tasks.isVisible()) {
                jScrollPane1Tasks.setVisible(false);
                jPanel5.remove(jScrollPane1Tasks);
            }
            
            jPanel5.add(jPanel6EmptyList);
            jPanel6EmptyList.setVisible(true);
            jPanel6EmptyList.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java Swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1TooBarTitle;
    private javax.swing.JLabel jLabel2ToolBarSubtitle;
    private javax.swing.JLabel jLabel3ProjectsTitle;
    private javax.swing.JLabel jLabel4TasksTitle;
    private javax.swing.JLabel jLabel5ProjectsAdd;
    private javax.swing.JLabel jLabel6TasksAdd;
    private javax.swing.JLabel jLabel7EmptyListaIcon;
    private javax.swing.JLabel jLabel8EmptyListTitle;
    private javax.swing.JLabel jLabel9EmptyListSubTitle;
    private javax.swing.JList<String> jList1Projects;
    private javax.swing.JPanel jPanel1ToolBar;
    private javax.swing.JPanel jPanel2Projects;
    private javax.swing.JPanel jPanel3Tasks;
    private javax.swing.JPanel jPanel4ProjectList;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6EmptyList;
    private javax.swing.JScrollPane jScrollPane1Projects;
    private javax.swing.JScrollPane jScrollPane1Tasks;
    private javax.swing.JTable jTable1TableTasks;
    // End of variables declaration//GEN-END:variables

    public void decotareTableTasks() {
        jTable1TableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineColumnCellRenderer());
        //Customizando o header da table de tarefas
        jTable1TableTasks.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        jTable1TableTasks.getTableHeader().setBackground(new Color(0,102,102));
        jTable1TableTasks.getTableHeader().setForeground(new Color(255,255,255));
        
        jTable1TableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineColumnCellRenderer());
        
//        jTable1TableTasks.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRederer("edit"));
//        jTable1TableTasks.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRederer("delete"));
        
        //Criando um sort automatico para ordenação das colunas da table
        //jTable1TableTasks.setAutoCreateRowSorter(true);
}
    public void initDataController() {
        projectController = new ProjectController();
        taskController = new TaskController();
        
    }
    
    public void initComponentsModel() {
        projecstModel = new DefaultListModel();
        loadProjects();
        
        taskModel = new TaskTableModel();
        jTable1TableTasks.setModel(taskModel);
        //loadTasks(2);
        
        if(!projecstModel.isEmpty()){
            jList1Projects.setSelectedIndex(0);
            Project project = (Project) projecstModel.get(0);
            loadTasks(project.getId());
        }
    }
    
    public void loadTasks(int idProject) {
        List<Task> tasks = taskController.getAll(idProject);
        taskModel.setTasks(tasks);
        showJTableTasks(!tasks.isEmpty());
    }
    
    public void loadProjects() {
        List<Project> projects = projectController.getAll();
        
        projecstModel.clear();
        
        for (int i = 0; i < projects.size(); i++) {
            
            Project project = projects.get(i);
            
            projecstModel.addElement(project); 
        }
        jList1Projects.setModel(projecstModel);
    }

}
